version: "3.9"

services:
  mqtt:
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ./certs/letsencrypt:/certs:ro
      - ./appdata/passwords:/passwords
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    build: ./mqtt

  sensor_logger:
    container_name: sensor_logger
    restart: unless-stopped
    build:
      context: ./sensor_logger
      dockerfile: sensor_logger.dockerfile
    env_file: .env
    volumes:
      - /sys:/sys
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./appdata:/appdata
      - ./pymodules:/app/pymodules
      - ./appdata/certbot/letsencrypt:/etc/letsencrypt/
      - ./sensor_logger:/app
    depends_on:
      - mqtt
    ports:
      - 42660:42660
    command: python3 main.py

  mqtt_bridge_client:
    container_name: mqtt_bridge_client
    restart: unless-stopped
    build:
      context: ./mqtt_bridge_client
      dockerfile: mqtt_bridge_client.dockerfile
    env_file: .env
    volumes:
      - ./pymodules:/app/pymodules
      - ./mqtt_bridge_client:/app
    depends_on:
      - mqtt
    command: python3 main.py --port 42668

  ntp_server:
    container_name: ntp_server
    build:
      context: ./ntp_server
      dockerfile: ntp_server.dockerfile
    volumes:
      - ./ntp_server:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 123:123/udp
    restart: unless-stopped
    command: python3 main.py

  ddns:
    container_name: ddns
    build:
      context: ./ddns
      dockerfile: ddns.dockerfile
    env_file: .env
    volumes:
      - ./ddns:/app
    restart: unless-stopped
    command: python3 main.py --hrs 1
    network_mode: host

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:arm32v6-latest
  #   volumes:
  #     - ./certs/letsencrypt:/etc/letsencrypt
  #   restart: unless-stopped
  #   entrypoint: >
  #     /bin/sh
  #     -c
  #     'trap exit TERM;
  #     while :;
  #     do certbot renew --noninteractive --standalone --quiet;
  #     chmod -R 777 /etc/letsencrypt/;
  #     sleep 12h & wait $${!};
  #     done;'
