version: '3.9'
# Run before ipv6
# docker network create --ipv6 --subnet=fd00::/64 prodnet
services:
    ipv6nat:
        container_name: ipv6nat
        restart: always
        image: robbertkl/ipv6nat:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /lib/modules:/lib/modules:ro
        privileged: true
        network_mode: "host"

    mqtt:
        container_name: mqtt
        restart: always
        build: ./mqtt
        ports:
            - 1883:1883
        networks:
            - prodnet

    sensor_logger:
        container_name: sensor_logger
        restart: always
        build: ./sensor_logger
        volumes:
            - /sys:/sys
            - /home/pi/appdata:/db
            - /home/pi/appdata/certbot/letsencrypt:/etc/letsencrypt/
        depends_on:
            - mqtt
        ports:
            - 42660:42660
            - 42661:42661
        privileged: true
        networks:
            - prodnet

    ddns:
        container_name: ddns
        restart: always
        build: ./ddns
        network_mode: host

    certbot:
        image: certbot/certbot:arm32v6-latest
        container_name: certbot
        restart: always
        ports:
            - 80:80
        volumes:
            - /home/pi/appdata/certbot/letsencrypt:/etc/letsencrypt
            - /home/pi/appdata/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew -n ; sleep 24h & wait $${!}; done;'"

networks:
    prodnet:
        external: true